version: '2'
services:

  mysql:
    hostname: mysql
    image: 'mysql:5.7'
    environment:
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
