name: upload
description: "Upload test results and reports."
inputs:
  name-suffix:
    default: ${{ github.job }}
  upload-results:
    default: false
  test-report-retention-days:
    default: 5

runs:
  using: composite
  steps:
    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always() && inputs.upload-results
      with:
        name: result ${{ inputs.name-suffix }}
        if-no-files-found: 'ignore'
        path: |
          **/target/surefire-reports
          **/target/checkstyle-*
    - name: Upload test report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        # Name prefix is checked in the `Annotate checks` workflow
        name: test report ${{ inputs.name-suffix }}
        path: |
          **/surefire-reports/TEST-*.xml
        retention-days: ${{ inputs.test-report-retention-days }}
