databases:
  hive:
    host: hadoop-master
  presto:
    host: presto-master
    configured_hdfs_user: hive
    cli_truststore_path: /etc/openldap/certs/cacerts.jks
    cli_truststore_password: testldap
    cli_server_address: https://${databases.presto.host}:8443
