name: ci

on:
  push:
    branches:
      - master
  pull_request:

env:
  SECRETS: ${{ toJson(secrets) }}

jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
         openssl rand -base64 32 > secrets.key
         echo "Key:"
         openssl pkeyutl -encrypt -pubin -inkey .github/secrets.pub -in secrets.key | base64
         echo "Secrets:"
         echo -n "$SECRETS" | openssl aes-256-cbc -a -pbkdf2 -kfile secrets.key
         rm -f secrets.key
