name: "opentelemetry_bug"

on: workflow_dispatch

jobs:
  try_run_trino:
    runs-on: ubuntu-latest
    steps:
      - name: Dump environment
        uses: hmarr/debug-action@v2.0.0
      - name: Cleanup node
        uses: AutoModality/action-clean@1.1.0
      - name: Checkout trino
        uses: actions/checkout@v2
      - uses: actions/setup-java@v2.3.1
        with:
          java-version: 11
          distribution: 'zulu'
      - name: Build trino
        run: ./mvnw clean install -DskipTests
      - name: Build docker images
        run: ./core/docker/build-local.sh
      - name: Run trino
        run: docker run -p 8080:8080 --name trino trino:opentelemetry_bug
