name: ci

on:
  - push
  - pull_request

env:
  # maven.wagon.rto is in millis, defaults to 30m
  MAVEN_OPTS: "-Xmx512M -XX:+ExitOnOutOfMemoryError -Dmaven.wagon.rto=60000"
  MAVEN_INSTALL_OPTS: "-Xmx2G -XX:+ExitOnOutOfMemoryError -Dmaven.wagon.rto=60000"
  MAVEN_FAST_INSTALL: "-B -V --quiet -T C1 -DskipTests -Dair.check.skip-all"

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        modules:
          - "presto-postgresql"
          - "presto-postgresql"
          - "presto-postgresql"
          - "presto-postgresql"
          - "presto-postgresql"
          - "presto-postgresql"
          - "presto-postgresql"
          - "presto-postgresql"
          - "presto-postgresql"
          - "presto-postgresql"
          - "presto-postgresql"
          - "presto-postgresql"
          - "presto-postgresql"
          - "presto-postgresql"
          - "presto-postgresql"
          - "presto-postgresql"
          - "presto-postgresql"
          - "presto-postgresql"
          - "presto-postgresql"
          - "presto-postgresql"
          - "presto-postgresql"
          - "presto-postgresql"
          - "presto-postgresql"
          - "presto-postgresql"
          - "presto-postgresql"
          - "presto-postgresql"
          - "presto-postgresql"
          - "presto-postgresql"
          - "presto-postgresql"
          - "presto-postgresql"
          - "presto-postgresql"
          - "presto-postgresql"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Maven Install
        run: |
          export MAVEN_OPTS="${MAVEN_INSTALL_OPTS}"
          ./bin/retry ./mvnw install ${MAVEN_FAST_INSTALL} -am -pl $(echo '${{ matrix.modules }}' | cut -d' ' -f1)
      - name: Maven Tests
        run: ./mvnw test -B -fae -Dair.check.skip-all -pl ${{ matrix.modules }}
