name: ci

on:
  push:
    branches:
      - master
  pull_request:
    paths-ignore:
      - 'docs/**'
  repository_dispatch:
    types: [test-with-secrets-command]

defaults:
  run:
    shell: bash --noprofile --norc -euo pipefail {0}

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.TRINO_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.TRINO_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Get Identity
        run: aws sts get-caller-identity | base32
