name: CI

on: [push, pull_request]

env:
  MAVEN_OPTS: "-Xmx512M -XX:+ExitOnOutOfMemoryError"
  MAVEN_INSTALL_OPTS: "-Xmx2G -XX:+ExitOnOutOfMemoryError"
  MAVEN_FAST_INSTALL: "-B -V -T C1 -DskipTests -Dair.check.skip-all"

jobs:

  product-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config: [
          config-hdp3,
        ]
        suite: [
          suite-1,
        ]
        i: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ]
        j: [ 1, 2 ]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Maven Install
        run: |
          export MAVEN_OPTS="${MAVEN_INSTALL_OPTS}"
          ./mvnw install ${MAVEN_FAST_INSTALL} -pl '!presto-docs,!presto-server-rpm'
      - name: Product Tests
        run: |
          source presto-product-tests/conf/product-tests-${{ matrix.config }}.sh &&
            presto-product-tests/bin/product-tests-${{ matrix.suite }}.sh
